from django.urls import path
from . import views

app_name = 'adminpanel'

urlpatterns = [
    path('login/', views.admin_login, name='admin_login'),
    path('logout/', views.admin_logout, name='admin_logout'),
    path('', views.admin_dashboard, name='admin_dashboard'),
    path('students/', views.manage_students, name='manage_students'),
    path('students/<int:user_id>/toggle-status/', views.toggle_student_status, name='toggle_student_status'),
    path('students/<int:user_id>/profile/', views.student_profile, name='student_profile'),
    path('vendors/', views.manage_vendors, name='manage_vendors'),
    path('vendors/<int:user_id>/toggle-status/', views.toggle_vendor_status, name='toggle_vendor_status'),
    path('vendors/<int:user_id>/approve/', views.approve_vendor, name='approve_vendor'),
    path('vendors/<int:user_id>/reject/', views.reject_vendor, name='reject_vendor'),
    path('vendors/<int:user_id>/profile/', views.vendor_profile, name='vendor_profile'),
    path('delivery-boys/', views.manage_delivery_boys, name='manage_delivery_boys'),
    path('delivery-boys/<int:user_id>/toggle-status/', views.toggle_delivery_boy_status, name='toggle_delivery_boy_status'),
    path('delivery-boys/<int:user_id>/approve/', views.approve_delivery_boy, name='approve_delivery_boy'),
    path('delivery-boys/<int:user_id>/reject/', views.reject_delivery_boy, name='reject_delivery_boy'),
    path('delivery-boys/<int:user_id>/profile/', views.delivery_boy_profile, name='delivery_boy_profile'),
    path('messes/', views.manage_messes, name='manage_messes'),
    path('messes/<int:mess_id>/', views.mess_detail, name='mess_detail'),
    path('messes/<int:mess_id>/edit/', views.edit_mess, name='edit_mess'),
    path('messes/<int:mess_id>/toggle-status/', views.toggle_mess_status, name='toggle_mess_status'),
    path('messes/<int:mess_id>/approve/', views.approve_mess, name='approve_mess'),
    path('messes/<int:mess_id>/reject/', views.reject_mess, name='reject_mess'),
    path('messes/<int:mess_id>/delete/', views.delete_mess, name='delete_mess'),
    path('meals/', views.manage_meals, name='manage_meals'),
    path('meals/<int:meal_id>/', views.meal_detail, name='meal_detail'),
    path('meals/<int:meal_id>/edit/', views.edit_meal, name='edit_meal'),
    path('meals/<int:meal_id>/toggle-status/', views.toggle_meal_status, name='toggle_meal_status'),
    path('meals/<int:meal_id>/delete/', views.delete_meal, name='delete_meal'),
    path('orders/', views.manage_orders, name='manage_orders'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('orders/<int:order_id>/update-status/', views.update_order_status, name='update_order_status'),
    path('orders/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('subscriptions/', views.manage_subscriptions, name='manage_subscriptions'),
    path('subscriptions/<int:subscription_id>/', views.subscription_detail, name='subscription_detail'),
    path('subscriptions/<int:subscription_id>/activate/', views.activate_subscription, name='activate_subscription'),
    path('subscriptions/<int:subscription_id>/pause/', views.pause_subscription, name='pause_subscription'),
    path('subscriptions/<int:subscription_id>/resume/', views.resume_subscription, name='resume_subscription'),
    path('subscriptions/<int:subscription_id>/cancel/', views.cancel_subscription, name='cancel_subscription'),
    path('subscriptions/<int:subscription_id>/extend/', views.extend_subscription, name='extend_subscription'),
    path('complaints/', views.manage_complaints, name='manage_complaints'),
    path('complaints/<int:complaint_id>/', views.complaint_detail, name='complaint_detail'),
    path('complaints/<int:complaint_id>/update-status/', views.update_complaint_status, name='update_complaint_status'),
    path('complaints/<int:complaint_id>/resolve/', views.resolve_complaint, name='resolve_complaint'),
    path('complaints/<int:complaint_id>/close/', views.close_complaint, name='close_complaint'),
    path('analytics/', views.analytics_dashboard, name='analytics_dashboard'),
    path('analytics/export/csv/', views.export_analytics_csv, name='export_analytics_csv'),
    path('analytics/export/excel/', views.export_analytics_excel, name='export_analytics_excel'),
    path('ai-insights/', views.ai_insights, name='ai_insights'),
]
