# Generated by Django 5.2.11 on 2026-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/delivery_boys/'),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('cycle', 'Cycle'), ('scooter', 'Scooter'), ('other', 'Other')], default='bike', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
