# Generated by Django 5.2.11 on 2026-07-05 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    def generate_payment_ids(apps, schema_editor):
        import uuid
        Payment = apps.get_model('student', 'Payment')
        for payment in Payment.objects.filter(payment_id__isnull=True):
            payment.payment_id = uuid.uuid4()
            payment.save()

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='online', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(generate_payment_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Add Money'), ('debit', 'Payment/Debit'), ('cashback', 'Cashback Credit'), ('recharge', 'Recharge'), ('order_payment', 'Order Payment'), ('subscription_payment', 'Subscription Payment'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], max_length=25),
        ),
    ]
